version: '3.9'
services:

     
  web:
   image: productappserviceimage:latest
   build: 
     context: services/
     dockerfile: Dockerfile
   restart: always
   #network_mode: host
   container_name: productAppServiceContainer
   ports:
     - "8085:8085"
   expose:
     - "8085"
   healthcheck:
        test: "exit 0"     
  
  angular:
    image: productappuiimage:latest
    build: 
     context: Angular/
     dockerfile: Dockerfile
    #network_mode: host
    container_name: productAppUiContainer
    ports:
      - "80:80"
    expose:
     - "80"